name: CI Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run types

      - name: Build project
        run: npm run build

      - name: Deploy to server
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          curl -X POST http://209.222.97.95:4192/deploy \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.DEPLOYMENT_API_KEY }}" \
            -H "X-GitHub-Event: ${{ github.event_name }}" \
            -H "X-GitHub-Ref: ${{ github.ref }}" \
            -H "X-GitHub-SHA: ${{ github.sha }}" \
            -d '{
              "repository": "${{ github.repository }}",
              "branch": "${{ github.ref_name }}",
              "commit": "${{ github.sha }}",
              "event": "${{ github.event_name }}",
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
            }'
        continue-on-error: true
